CREATE TABLE Users (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL
);

CREATE TABLE Escalators (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE Incidents (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   escalator_id INTEGER NOT NULL,
   description TEXT NOT NULL,
   status VARCHAR(255) NOT NULL,
   date_begin DATETIME NOT NULL,
   date_end DATETIME NOT NULL,
   FOREIGN KEY (escalator_id) REFERENCES Escalators(id)
);
